import 'package:flutter/material.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLoginusingFacebookWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedGraphty123gmailcomWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedForgetPasswordWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLoginwithGoogleWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedConeWhiteGlossyWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedUsernameorEmailWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLogintoConitnueWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedConeWhiteGlossyWidget2.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedKeepmeSigninWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedOrIfyouareanewuserthencreateanewaccountWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget/generated/GeneratedConeWhiteGlossyWidget1.dart';

/* Frame Login_ Mobile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_MobileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 92.0,
                child: GeneratedWelcomeBackWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 21.0,
                child: GeneratedLogintoConitnueWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 24.0,
                child: GeneratedGraphty123gmailcomWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 16.0,
                child: GeneratedUsernameorEmailWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 24.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 19.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 2.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 2.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedKeepmeSigninWidget(),
              ),
              Positioned(
                left: 165.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 25.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 18.0,
                child: GeneratedOrIfyouareanewuserthencreateanewaccountWidget(),
              ),
              Positioned(
                left: 175.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 23.0,
                child: GeneratedORWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 66.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 66.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 18.0,
                child: GeneratedLoginusingFacebookWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 717.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 18.0,
                child: GeneratedLoginwithGoogleWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 40.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 40.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 31.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.01600985221674877;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 13.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8933333333333333,
                        translateY: constraints.maxHeight * 0.3805418719211823,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 57.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.14739742024739583;

                  final double height =
                      constraints.maxHeight * 0.07366373973526978;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.704,
                        y: constraints.maxHeight * 0.18539954876077586,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedConeWhiteGlossyWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06256893920898438;

                  final double height =
                      constraints.maxHeight * 0.031269625489934914;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9030598958333333,
                        y: constraints.maxHeight * 0.09405682944311884,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedConeWhiteGlossyWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.045299285888671874;

                  final double height =
                      constraints.maxHeight * 0.022638896415973532;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8275911458333334,
                        y: constraints.maxHeight * 0.08623324239195274,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedConeWhiteGlossyWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 16.0,
                child: GeneratedForgetPasswordWidget(),
              )
            ]),
      ),
    ));
  }
}
