import 'package:flutter/material.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedEmailAddressWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedThiswebsitewillsendyounewsupdatesandnotificationinyoure.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedConfirmPasswordWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedEmailAddressWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedFirstNameWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLastNameWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedPasswordWidget2.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedGroup30Widget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedAlreadyHaveanaccountLoginWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedCreateaNewAccountWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedDateOfBirthWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLastNameWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedDateOfBirthWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedFirstNameWidget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/misapp/generatedlogin_mobilewidget1/generated/GeneratedLine5Widget.dart';

/* Frame Login_ Mobile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_MobileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1118.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1118.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 31.0,
                              child: GeneratedRectangle7Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 205.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 22.0,
                              child: GeneratedFirstNameWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 16.0,
                              child: GeneratedFirstNameWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 235.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 1.0,
                              child: GeneratedLine1Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 22.0,
                              child: GeneratedLastNameWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 16.0,
                              child: GeneratedLastNameWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 1.0,
                              child: GeneratedLine2Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 22.0,
                              child: GeneratedEmailAddressWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 16.0,
                              child: GeneratedEmailAddressWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 457.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 1.0,
                              child: GeneratedLine3Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 22.0,
                              child: GeneratedDateOfBirthWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 16.0,
                              child: GeneratedDateOfBirthWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 551.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 1.0,
                              child: GeneratedLine5Widget(),
                            ),
                            Positioned(
                              left: 698.0,
                              top: 634.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 8.0,
                              child: GeneratedVector6Widget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 618.0,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 66.0,
                              child: GeneratedGroup50Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 768.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 31.0,
                              child: GeneratedPasswordWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 19.0,
                              child: GeneratedPasswordWidget2(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 806.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 2.0,
                              child: GeneratedLine6Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 861.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 28.0,
                              child: GeneratedConfirmPasswordWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 839.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 16.0,
                              child: GeneratedConfirmPasswordWidget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 899.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 2.0,
                              child: GeneratedLine7Widget(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 977.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 33.0,
                              child: GeneratedCreateaNewAccountWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 935.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 57.0,
                              child: GeneratedGroup30Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 189.0,
                              height: 54.0,
                              child: GeneratedRegisterWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 1020.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 13.0,
                              child: GeneratedAlreadyHaveanaccountLoginWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
